### ISSUE TITLE
Sampling using DDIM

### ISSUE THREAD

**Issue by ndhieunguyen** [CRIPAC-DIG/tgm-dlm#3]
In the training process, you use 2000 diffusion steps to train the model, so in the inferencing process, you use 2000 diffusion steps with DDPM to get the result. Then if I use DDIM, how many steps should I use?

**Comment by Deno-V** [comment]
Not exactly. In the implementation part of the paper, I described the sampling method I used in the generation process. I did not really use 2000 denoise steps. 200 steps is employed by using SpacedDiffusion (You can check this in improved-diffusion/respace.py). It behaves like skipping steps in the sampling process. As for DDIM, I am not very sure about its performance. I guess there will be no big difference.
