### ISSUE TITLE
train.py error

### ISSUE THREAD

**Issue by Qlalq** [CRIPAC-DIG/tgm-dlm#4]
Probably deleted it by mistake when writing the note :)  

File "tgm-dlm-main/improved-diffusion/scripts/train.py", line 155
    lr = 0.00005
         ^^^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?

**Comment by Deno-V** [comment]
I am sorry! Last update I just changed this and forgot comma. Thanks.
