### ISSUE TITLE
Requirement.txt

### ISSUE THREAD

**Issue by Qlalq** [CRIPAC-DIG/tgm-dlm#5]
Requirement.txt would make the experience much better, if possible :)

**Comment by Deno-V** [comment]
I think no special packages is used, so I didn't record the requirement.txt. No special environment is needed, except for following the README.md to properly install improved-diffusion and transformers (this transformers is different from the one provided by huggingface. It has been modified). No more to note I think, just regular python3 and PyTorch, Wandb. The latest versions should be fine. If any problem comes to you, please let me know, thanks.
