### ISSUE TITLE
ValueError: not enough values to unpack (expected 2, got 1)

### ISSUE THREAD

**Issue by Cello2195** [CRIPAC-DIG/tgm-dlm#6]
When I run "python post_sample.py", it came to me that:
Traceback (most recent call last):
  File "post_sample.py", line 208, in <module>
    main()
  File "post_sample.py", line 150, in main
    for (num,smiles) in tochange:
ValueError: not enough values to unpack (expected 2, got 1)

**Comment by Deno-V** [comment]
Are you really sure? I am confused about this Error.

Your error line is: `for (num, smiles) in tochange:`
which means `tochange` is somewhat wrong.
However `tochange` is from just several lines before this line: 
`with open(args.outputdir) as f:
    tochange = [k.strip().split() for k in f.readlines()]`
While each row of the `args.outputdir` file's content is written by `f.write(orders[i]+'\t'+x.replace('[PAD]','')+'\n')`.

So each row of args.outputdir should be a number and a '\t' and a SMILES string, that is to say `tochange` is a list with each element being [a number , a SMILES].  Therefore there should not be an error in `for (num,smles) in tochange:`

I am confused, could you please provide me with more information? for example print(tochange) just right before this error line?
There's a chance that the `x.replace('[PAD]','')` in `f.write(orders[i]+'\t'+x.replace('[PAD]','')+'\n')` is empty that can lead to this error. Please check it, thanks. You can email me gonghaisong2021@ia.ac.cn where I may find your message more promptly.

**Comment by Deno-V** [comment]
After discussion, this problem occurs because the training of phase 2 collapses. I guess it's because bad learning rate so I lowered it.
